#!/bin/sh

case "$1" in
    start)
        echo "Starting snake"
        start-stop-daemon -S -n snake -a /usr/bin/snake -- -d
        ;;
    stop)
        echo "Stopping snake"
        start-stop-daemon -K -n snake
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0